### ISSUE TITLE
Improve organization

### ISSUE THREAD

**Issue by JelleZijlstra** [JelleZijlstra/typing-spec#2]
The current top-level organization of the spec is mostly inherited from PEP 484, but I don't like it much. Let's use this issue to discuss ways to improve the organization.

One idea:

- First a top-level section discussing the overall features of the type system (using annotations, general subtyping rules, etc.)
- Then top-level section for each "feature", mostly corresponding to names in the typing module
- Then extra sections describing features not directly tied to specific names in typing: stub files, PEP 561, etc.
- A section discussing important related projects: the `typing` module, `typing_extensions`, typeshed
- The "Syntax alternatives" section discussing old syntax

**Comment by NeilGirdhar** [comment]
Looks awesome so far.

Some ideas about organization:

- You may want to consider moving outdated features to their own section to keep the specification as short as possible.  For example `TypeVar` will soon be replaced by 695.   Should the PEP 695 way of doing things be shown first?  Someone new to typing, but using Python 3.12, should be nudged towards PEP 695, right?
- You may want to link to relevant discussions including typing PEP discussion and github issues for each type features so that people can research "why" a given behavior was chosen.  Whereas the specification answers "what" behavior was chosen, knowing why is important before asking questions or suggesting changes.  This can help typing maintainers from having to keep answering the same questions?

**Comment by JelleZijlstra** [comment]
Thanks!

I think I'm already doing what your first point suggests: the "Syntax alternatives" section (better names welcome) at the end lists outdated syntax. For example, in this commit I moved the old pos-only syntax there: https://github.com/JelleZijlstra/typing-spec/commit/a02257a81ac3b9d5519e2be23fc2a7f8898dd11d. I will do something similar when I get to PEP 695.

Your second suggestion, essentially annotating the spec with a reading list of relevant discussions, sounds useful, but it's also a lot of work and not strictly part of the spec itself. I have been adding links to relevant PEPs already, but collecting links for other kinds of discussions is out of scope for now.

**Comment by NeilGirdhar** [comment]
> sounds useful, but it's also a lot of work and not strictly part of the spec itself.

Fair enough.  If you show that contributions are welcome, people may start adding the links for you?  (Just as an example, there was that gigantic discussion about why `X & Any` is not `X` and similarly why `X | Any` is not `Any`.)  I guess you could just add links as questions repeatedly come up if you decide that they're in scope.

**Comment by JelleZijlstra** [comment]
Sure, I'd accept contributions that add such links. The section on Unions (https://github.com/JelleZijlstra/typing-spec/blob/main/spec/spec.rst#union-types) is very thin indeed :)

**Comment by JelleZijlstra** [comment]
Ended up with  going something slightly different in #8, but I think it works well as a basis to work from.
